version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "6306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vbhuvZ82aruEchec
      MYSQL_DATABASE: nexty-local
  nexty-web:
    build: .
    container_name: nexty-web
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - mysql
    env_file:
      - ".env"
    command: "npm run watch"
    ports:
      - "3000:3000"
    tty: true

volumes:
  db-data:
