branch-defaults:
  develop:
    environment: nexty-staging
environment-defaults:
  nexty-staging:
    branch: null
    repository: null
global:
  application_name: nexty-dev
  default_ec2_keyname: nexty
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Node.js running
    on 64bit Amazon Linux/4.5.1
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: nexty
  sc: git
  workspace_type: Application
